language: node_js
node_js:
  - 8.12.0

branches:
  only:
  - master

services:
  - docker

env:
  - NODE_ENV=development

before_install:

install:
  - npm install -g grunt-cli typescript && npm install

before_script:

script:
  - grunt lib
  - grunt website
  - grunt doc

after_script:
